trigger:
  branches:
    include:
      - main  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'  # Using Ubuntu as the agent image

variables:
  azureSubscription: 'YourAzureSubscriptionName'  # Azure Subscription linked in Azure DevOps
  appName: 'webapptest00'  # Name of the Azure Web App
  resourceGroup: 'YourResourceGroup'  # Resource Group name for your Azure Web App

jobs:
  - job: BuildAndDeploy
    displayName: 'Build and Deploy .NET Core to Azure'
    steps:

      - task: Checkout@2  # Checkout the code from the repository
        displayName: 'Checkout Code'

      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.x'  # Specify the .NET version
        displayName: 'Install .NET SDK'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'  # Restore dependencies
          projects: '**/*.csproj'  # Path to your .csproj files
        displayName: 'Restore dependencies'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'  # Build the app
          projects: '**/*.csproj'  # Path to your .csproj files
        displayName: 'Build the project'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'  # Publish the app
          publishWebProjects: true
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/publish'
        displayName: 'Publish the project'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)/publish'
          artifactName: 'drop'
        displayName: 'Publish Artifact'

  - job: DeployToAzure
    displayName: 'Deploy to Azure Web App'
    dependsOn: BuildAndDeploy  # Ensure deploy job runs after the build
    condition: succeeded()
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: 'drop'
        displayName: 'Download Artifact'

      - task: AzureWebApp@1
        inputs:
          azureSubscription: $(azureSubscription)  # Azure Subscription name
          appName: $(appName)  # Azure Web App name
          package: $(Build.ArtifactStagingDirectory)/publish  # Path to the published app
        displayName: 'Deploy to Azure Web App'
